CREATE TABLE `account_simple` (
	`order_no` VARCHAR(22) NOT NULL,
	`nama` VARCHAR(50) NOT NULL,
	`tempat_lahir` VARCHAR(50) NOT NULL,
	`day` INT(2) NOT NULL DEFAULT '0',
	`month` INT(2) NOT NULL DEFAULT '0',
	`year` INT(4) NOT NULL DEFAULT '0',
	`id_type` TINYINT(1) NOT NULL,
	`id_no` VARCHAR(25) NOT NULL,
	`npwp_type` TINYINT(1) NOT NULL DEFAULT '0',
	`npwp_no` VARCHAR(20) NOT NULL,
	`kelamin` TINYINT(1) NOT NULL,
	`nama_pasangan` VARCHAR(50) NOT NULL,
	`nama_ibu` VARCHAR(50) NOT NULL,
	`status_kawin` TINYINT(1) NOT NULL,
	`alm_rumah1` VARCHAR(255) NOT NULL,
	`alm_rumah2` VARCHAR(50) NOT NULL,
	`alm_rumah3` VARCHAR(50) NOT NULL,
	`kode_pos_rumah` INT(9) NOT NULL,
	`no_telp_rumah` BIGINT(15) NOT NULL,
	`no_fax_rumah` BIGINT(15) NOT NULL,
	`no_hp` BIGINT(15) NOT NULL,
	`status_rumah` TINYINT(1) NOT NULL,
	`ket_rumah` VARCHAR(25) NOT NULL,
	`tujuan_buka_acc` TINYINT(1) NOT NULL,
	`tujuan_buka_acc_ket` VARCHAR(50) NOT NULL,
	`pengalaman_inv` TINYINT(1) NOT NULL,
	`pengalaman_inv_ket` VARCHAR(50) NOT NULL,
	`pengalaman_trans` TINYINT(1) NOT NULL,
	`keluarga_bapebti` TINYINT(1) NOT NULL,
	`pailit` TINYINT(1) NOT NULL,
	`darurat_nama` VARCHAR(50) NOT NULL,
	`darurat_alm_rumah1` VARCHAR(255) NOT NULL,
	`darurat_alm_rumah2` VARCHAR(50) NOT NULL,
	`darurat_alm_rumah3` VARCHAR(50) NOT NULL,
	`darurat_kode_pos` INT(9) NOT NULL,
	`darurat_telp` BIGINT(15) NOT NULL,
	`darurat_hub` VARCHAR(25) NOT NULL,
	`pekerjaan` TINYINT(1) NOT NULL,
	`pekerjaan_ket` VARCHAR(50) NOT NULL,
	`nama_persh` VARCHAR(50) NOT NULL,
	`bidang_usaha` VARCHAR(25) NOT NULL,
	`jabatan` VARCHAR(25) NOT NULL,
	`lama_kerja` TINYINT(2) NOT NULL,
	`lama_sebelumnya` TINYINT(2) NOT NULL,
	`alm_kantor1` VARCHAR(255) NOT NULL,
	`alm_kantor2` VARCHAR(50) NOT NULL,
	`alm_kantor3` VARCHAR(50) NOT NULL,
	`kode_pos_kantor` INT(9) NOT NULL,
	`telp_kantor` BIGINT(15) NOT NULL,
	`fax_kantor` BIGINT(15) NOT NULL,
	`penghasilan` SMALLINT(1) NOT NULL,
	`kekayaan` VARCHAR(50) NOT NULL,
	`rumah_lokasi` VARCHAR(50) NOT NULL,
	`nilai_njop` BIGINT(15) NOT NULL,
	`deposit_bank_name` VARCHAR(50) NOT NULL DEFAULT '',
	`deposit_bank` BIGINT(15) NOT NULL,
	`jumlah` BIGINT(15) NOT NULL,
	`lainnya` BIGINT(15) NOT NULL,
	`nama_bank` VARCHAR(50) NOT NULL,
	`cabang_bank` VARCHAR(50) NOT NULL,
	`no_acc_bank` VARCHAR(20) NOT NULL,
	`no_telp_bank1` BIGINT(15) NOT NULL,
	`atas_nama_bank` VARCHAR(50) NOT NULL,
	`jenis_tabungan1` SMALLINT(1) NOT NULL,
	`jenis_tabungan1_ket` VARCHAR(25) NOT NULL,
	`nama_bank2` VARCHAR(50) NULL DEFAULT NULL,
	`cabang_bank2` VARCHAR(50) NULL DEFAULT NULL,
	`no_acc_bank2` VARCHAR(50) NULL DEFAULT NULL,
	`no_telp_bank2` BIGINT(15) NULL DEFAULT NULL,
	`atas_nama_bank2` VARCHAR(50) NULL DEFAULT NULL,
	`jenis_tabungan2` SMALLINT(1) NULL DEFAULT NULL,
	`jenis_tabungan2_ket` VARCHAR(25) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`pathdir` VARCHAR(6) NULL DEFAULT NULL,
	`perselisihan` SMALLINT(1) NOT NULL DEFAULT '0',
	`pengadilan` VARCHAR(30) NULL DEFAULT NULL,
	`cabang` INT(1) NOT NULL DEFAULT '0',
	`PBKCDDS01` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS021` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS022` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS03` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS04` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS051` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS052` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS061` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS062` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS07` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS08` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS09` INT(10) NOT NULL DEFAULT '0',
	`PBKCDDS10` INT(10) NOT NULL DEFAULT '0',
	`MODIFY_TIME` BIGINT(20) NOT NULL DEFAULT '0',
	PRIMARY KEY (`order_no`)
);