Table "account_corporate_del" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "alamat_persh1" VARCHAR(50) [not null]
  "alamat_persh2" VARCHAR(50) [not null]
  "alamat_persh3" VARCHAR(50) [not null]
  "kodepos_persh" INT(9) [not null]
  "telp_persh" BIGINT(15) [not null]
  "fax_persh" BIGINT(15) [not null]
  "hp_persh" BIGINT(15) [not null]
  "email_persh" VARCHAR(50) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_rekening" SMALLINT(1) [not null]
  "jenis_rekening_ket" VARCHAR(25) [not null]
  "pemegang_saham1" VARCHAR(50) [not null]
  "pemegang_saham2" VARCHAR(50) [not null]
  "pemegang_saham3" VARCHAR(50) [not null]
  "pemegang_saham4" VARCHAR(50) [not null]
  "nama_pengurus1" VARCHAR(50) [not null]
  "jabatan_pengurus1" VARCHAR(25) [not null]
  "alamat_pengurus1" VARCHAR(100) [not null]
  "telp_pengurus1" BIGINT(15) [not null]
  "fax_pengurus1" BIGINT(15) [not null]
  "id_type_pengurus1" SMALLINT(1) [not null]
  "id_no_pengurus1" VARCHAR(25) [not null]
  "nama_pengurus2" VARCHAR(50) [not null]
  "jabatan_pengurus2" VARCHAR(25) [not null]
  "alamat_pengurus2" VARCHAR(100) [not null]
  "telp_pengurus2" BIGINT(15) [not null]
  "fax_pengurus2" BIGINT(15) [not null]
  "id_type_pengurus2" SMALLINT(1) [not null]
  "id_no_pengurus2" VARCHAR(25) [not null]
  "nama_pengurus3" VARCHAR(50) [not null]
  "jabatan_pengurus3" VARCHAR(25) [not null]
  "alamat_pengurus3" VARCHAR(100) [not null]
  "telp_pengurus3" BIGINT(15) [not null]
  "fax_pengurus3" BIGINT(15) [not null]
  "id_type_pengurus3" SMALLINT(1) [not null]
  "id_no_pengurus3" VARCHAR(25) [not null]
  "nama_pengurus4" VARCHAR(50) [not null]
  "jabatan_pengurus4" VARCHAR(25) [not null]
  "alamat_pengurus4" VARCHAR(100) [not null]
  "telp_pengurus4" BIGINT(15) [not null]
  "fax_pengurus4" BIGINT(15) [not null]
  "id_type_pengurus4" SMALLINT(1) [not null]
  "id_no_pengurus4" VARCHAR(25) [not null]
  "nama_pejabat" VARCHAR(50) [not null]
  "jabatan_pejabat" VARCHAR(25) [not null]
  "alamat_pejabat" VARCHAR(100) [not null]
  "telp_pejabat" BIGINT(15) [not null]
  "fax_pejabat" BIGINT(15) [not null]
  "id_type_pejabat" SMALLINT(1) [not null]
  "id_no_pejabat" VARCHAR(25) [not null]
  "pathdir" VARCHAR(6) [not null]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [not null]
}

Table "account_corporate" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "alamat_persh1" VARCHAR(50) [not null]
  "alamat_persh2" VARCHAR(50) [not null]
  "alamat_persh3" VARCHAR(50) [not null]
  "kodepos_persh" INT(9) [not null]
  "telp_persh" BIGINT(15) [not null]
  "fax_persh" BIGINT(15) [not null]
  "hp_persh" BIGINT(15) [not null]
  "email_persh" VARCHAR(50) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_rekening" SMALLINT(1) [not null]
  "jenis_rekening_ket" VARCHAR(25) [not null]
  "pemegang_saham1" VARCHAR(50) [not null]
  "pemegang_saham2" VARCHAR(50) [not null]
  "pemegang_saham3" VARCHAR(50) [not null]
  "pemegang_saham4" VARCHAR(50) [not null]
  "nama_pengurus1" VARCHAR(50) [not null]
  "jabatan_pengurus1" VARCHAR(25) [not null]
  "alamat_pengurus1" VARCHAR(100) [not null]
  "telp_pengurus1" BIGINT(15) [not null]
  "fax_pengurus1" BIGINT(15) [not null]
  "id_type_pengurus1" SMALLINT(1) [not null]
  "id_no_pengurus1" VARCHAR(25) [not null]
  "nama_pengurus2" VARCHAR(50) [not null]
  "jabatan_pengurus2" VARCHAR(25) [not null]
  "alamat_pengurus2" VARCHAR(100) [not null]
  "telp_pengurus2" BIGINT(15) [not null]
  "fax_pengurus2" BIGINT(15) [not null]
  "id_type_pengurus2" SMALLINT(1) [not null]
  "id_no_pengurus2" VARCHAR(25) [not null]
  "nama_pengurus3" VARCHAR(50) [not null]
  "jabatan_pengurus3" VARCHAR(25) [not null]
  "alamat_pengurus3" VARCHAR(100) [not null]
  "telp_pengurus3" BIGINT(15) [not null]
  "fax_pengurus3" BIGINT(15) [not null]
  "id_type_pengurus3" SMALLINT(1) [not null]
  "id_no_pengurus3" VARCHAR(25) [not null]
  "nama_pengurus4" VARCHAR(50) [not null]
  "jabatan_pengurus4" VARCHAR(25) [not null]
  "alamat_pengurus4" VARCHAR(100) [not null]
  "telp_pengurus4" BIGINT(15) [not null]
  "fax_pengurus4" BIGINT(15) [not null]
  "id_type_pengurus4" SMALLINT(1) [not null]
  "id_no_pengurus4" VARCHAR(25) [not null]
  "nama_pejabat" VARCHAR(50) [not null]
  "jabatan_pejabat" VARCHAR(25) [not null]
  "alamat_pejabat" VARCHAR(100) [not null]
  "telp_pejabat" BIGINT(15) [not null]
  "fax_pejabat" BIGINT(15) [not null]
  "id_type_pejabat" SMALLINT(1) [not null]
  "id_no_pejabat" VARCHAR(25) [not null]
  "pathdir" VARCHAR(6) [not null]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [not null]
}

Table "account_marketing_backup" {
  "acc" INT(11) [not null]
  "platform" VARCHAR(10) [not null, default: "mt4"]
  "marketing" INT(11) [not null, default: "0"]
  "maintenance" INT(11) [not null, default: "0"]
  "active" TINYINT(4) [not null]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]
}

Table "account_marketing_fx" {
  "acc" INT(11) [not null]
  "platform" VARCHAR(10) [not null, default: "mt4"]
  "marketing" INT(11) [not null, default: "0"]
  "active" TINYINT(4) [not null]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]
}

Table "account_marketing_mtc" {
  "acc" VARCHAR(20) [not null]
  "platform" VARCHAR(10) [not null, default: "mt4"]
  "marketing" INT(11) [not null, default: "0", note: 'maintenance']
  "active" DATETIME [not null]
  "chop" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]

Indexes {
  acc [name: "mt4acc"]
  marketing [name: "marketing"]
}
}

Table "account_marketing" {
  "acc" VARCHAR(20) [not null]
  "platform" VARCHAR(10) [not null, default: "mt4"]
  "marketing" INT(11) [not null, default: "0", note: 'follow-up']
  "active" DATETIME [not null]
  "chop" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]

Indexes {
  acc [name: "mt4acc"]
  marketing [name: "marketing"]
}
}

Table "account_personal_del" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "tempat_lahir" VARCHAR(50) [not null]
  "day" INT(2) [not null]
  "month" INT(2) [not null]
  "year" INT(4) [not null]
  "id_type" TINYINT(1) [not null]
  "id_no" VARCHAR(25) [not null]
  "npwp_type" TINYINT(1) [not null, default: "0"]
  "npwp_no" VARCHAR(20) [not null]
  "kelamin" TINYINT(1) [not null]
  "nama_pasangan" VARCHAR(50) [not null]
  "nama_ibu" VARCHAR(50) [not null]
  "status_kawin" TINYINT(1) [not null]
  "alm_rumah1" VARCHAR(255) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_telp_rumah" BIGINT(15) [not null]
  "no_fax_rumah" BIGINT(15) [not null]
  "no_hp" BIGINT(15) [not null]
  "status_rumah" TINYINT(1) [not null]
  "ket_rumah" VARCHAR(25) [not null]
  "tujuan_buka_acc" TINYINT(1) [not null]
  "tujuan_buka_acc_ket" VARCHAR(50) [not null]
  "pengalaman_inv" TINYINT(1) [not null]
  "pengalaman_inv_ket" VARCHAR(50) [not null]
  "keluarga_bapebti" TINYINT(1) [not null]
  "pailit" TINYINT(1) [not null]
  "darurat_nama" VARCHAR(50) [not null]
  "darurat_alm_rumah1" VARCHAR(255) [not null]
  "darurat_alm_rumah2" VARCHAR(50) [not null]
  "darurat_alm_rumah3" VARCHAR(50) [not null]
  "darurat_kode_pos" INT(9) [not null]
  "darurat_telp" BIGINT(15) [not null]
  "darurat_hub" VARCHAR(25) [not null]
  "pekerjaan" TINYINT(1) [not null]
  "pekerjaan_ket" VARCHAR(50) [not null]
  "nama_persh" VARCHAR(50) [not null]
  "bidang_usaha" VARCHAR(25) [not null]
  "jabatan" VARCHAR(25) [not null]
  "lama_kerja" TINYINT(2) [not null]
  "lama_sebelumnya" TINYINT(2) [not null]
  "alm_kantor1" VARCHAR(255) [not null]
  "alm_kantor2" VARCHAR(50) [not null]
  "alm_kantor3" VARCHAR(50) [not null]
  "kode_pos_kantor" INT(9) [not null]
  "telp_kantor" BIGINT(15) [not null]
  "fax_kantor" BIGINT(15) [not null]
  "penghasilan" SMALLINT(1) [not null]
  "kekayaan" VARCHAR(50) [not null]
  "rumah_lokasi" VARCHAR(50) [not null]
  "nilai_njop" BIGINT(15) [not null]
  "deposit_bank" BIGINT(15) [not null]
  "jumlah" BIGINT(15) [not null]
  "lainnya" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "no_telp_bank1" BIGINT(15) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_tabungan1" SMALLINT(1) [not null]
  "jenis_tabungan1_ket" VARCHAR(25) [not null]
  "nama_bank2" VARCHAR(50) [not null]
  "cabang_bank2" VARCHAR(50) [not null]
  "no_acc_bank2" VARCHAR(50) [not null]
  "no_telp_bank2" BIGINT(15) [not null]
  "atas_nama_bank2" VARCHAR(50) [not null]
  "jenis_tabungan2" SMALLINT(1) [not null]
  "jenis_tabungan2_ket" VARCHAR(25) [not null]
  "email" VARCHAR(50) [not null]
  "pathdir" VARCHAR(6) [not null]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [not null]
  "cabang" INT(1) [not null, default: "0"]
  "107PBK01" INT(10) [not null, default: "0"]
  "107PBK021" INT(10) [not null, default: "0"]
  "107PBK022" INT(10) [not null, default: "0"]
  "107PBK03" INT(10) [not null, default: "0"]
  "107PBK041" INT(10) [not null, default: "0"]
  "107PBK042" INT(10) [not null, default: "0"]
  "107PBK051" INT(10) [not null, default: "0"]
  "107PBK052" INT(10) [not null, default: "0"]
  "107PBK06" INT(10) [not null, default: "0"]
  "107PBK07" INT(10) [not null, default: "0"]
  "MODIFY_TIME" BIGINT(20) [not null]
}

Table "account_personal_fx" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "tempat_lahir" VARCHAR(50) [not null]
  "day" INT(2) [not null]
  "month" INT(2) [not null]
  "year" INT(4) [not null]
  "id_type" TINYINT(1) [not null]
  "id_no" VARCHAR(25) [not null]
  "npwp_type" TINYINT(1) [not null, default: "0"]
  "npwp_no" VARCHAR(20) [not null]
  "kelamin" TINYINT(1) [not null]
  "nama_pasangan" VARCHAR(50) [not null]
  "nama_ibu" VARCHAR(50) [not null]
  "status_kawin" TINYINT(1) [not null]
  "alm_rumah1" VARCHAR(255) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_telp_rumah" BIGINT(15) [not null]
  "no_fax_rumah" BIGINT(15) [not null]
  "no_hp" BIGINT(15) [not null]
  "status_rumah" TINYINT(1) [not null]
  "ket_rumah" VARCHAR(25) [not null]
  "tujuan_buka_acc" TINYINT(1) [not null]
  "tujuan_buka_acc_ket" VARCHAR(50) [not null]
  "pengalaman_inv" TINYINT(1) [not null]
  "pengalaman_inv_ket" VARCHAR(50) [not null]
  "keluarga_bapebti" TINYINT(1) [not null]
  "pailit" TINYINT(1) [not null]
  "darurat_nama" VARCHAR(50) [not null]
  "darurat_alm_rumah1" VARCHAR(255) [not null]
  "darurat_alm_rumah2" VARCHAR(50) [not null]
  "darurat_alm_rumah3" VARCHAR(50) [not null]
  "darurat_kode_pos" INT(9) [not null]
  "darurat_telp" BIGINT(15) [not null]
  "darurat_hub" VARCHAR(25) [not null]
  "pekerjaan" TINYINT(1) [not null]
  "pekerjaan_ket" VARCHAR(50) [not null]
  "nama_persh" VARCHAR(50) [not null]
  "bidang_usaha" VARCHAR(25) [not null]
  "jabatan" VARCHAR(25) [not null]
  "lama_kerja" TINYINT(2) [not null]
  "lama_sebelumnya" TINYINT(2) [not null]
  "alm_kantor1" VARCHAR(255) [not null]
  "alm_kantor2" VARCHAR(50) [not null]
  "alm_kantor3" VARCHAR(50) [not null]
  "kode_pos_kantor" INT(9) [not null]
  "telp_kantor" BIGINT(15) [not null]
  "fax_kantor" BIGINT(15) [not null]
  "penghasilan" SMALLINT(1) [not null]
  "kekayaan" VARCHAR(50) [not null]
  "rumah_lokasi" VARCHAR(50) [not null]
  "nilai_njop" BIGINT(15) [not null]
  "deposit_bank" BIGINT(15) [not null]
  "jumlah" BIGINT(15) [not null]
  "lainnya" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "no_telp_bank1" BIGINT(15) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_tabungan1" SMALLINT(1) [not null]
  "jenis_tabungan1_ket" VARCHAR(25) [not null]
  "nama_bank2" VARCHAR(50) [not null]
  "cabang_bank2" VARCHAR(50) [not null]
  "no_acc_bank2" VARCHAR(50) [not null]
  "no_telp_bank2" BIGINT(15) [not null]
  "atas_nama_bank2" VARCHAR(50) [not null]
  "jenis_tabungan2" SMALLINT(1) [not null]
  "jenis_tabungan2_ket" VARCHAR(25) [not null]
  "email" VARCHAR(50) [not null]
  "pathdir" VARCHAR(6) [not null]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [not null]
  "cabang" INT(1) [not null, default: "0"]
  "107PBK01" INT(10) [not null, default: "0"]
  "107PBK021" INT(10) [not null, default: "0"]
  "107PBK022" INT(10) [not null, default: "0"]
  "107PBK03" INT(10) [not null, default: "0"]
  "107PBK041" INT(10) [not null, default: "0"]
  "107PBK042" INT(10) [not null, default: "0"]
  "107PBK051" INT(10) [not null, default: "0"]
  "107PBK052" INT(10) [not null, default: "0"]
  "107PBK06" INT(10) [not null, default: "0"]
  "107PBK07" INT(10) [not null, default: "0"]
}

Table "account_personal" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "tempat_lahir" VARCHAR(50) [not null]
  "day" INT(2) [not null]
  "month" INT(2) [not null]
  "year" INT(4) [not null]
  "id_type" TINYINT(1) [not null]
  "id_no" VARCHAR(25) [not null]
  "npwp_type" TINYINT(1) [not null, default: "0"]
  "npwp_no" VARCHAR(20) [not null]
  "kelamin" TINYINT(1) [not null]
  "nama_pasangan" VARCHAR(50) [not null]
  "nama_ibu" VARCHAR(50) [not null]
  "status_kawin" TINYINT(1) [not null]
  "alm_rumah1" VARCHAR(255) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_telp_rumah" BIGINT(15) [not null]
  "no_fax_rumah" BIGINT(15) [not null]
  "no_hp" BIGINT(15) [not null]
  "status_rumah" TINYINT(1) [not null]
  "ket_rumah" VARCHAR(25) [not null]
  "tujuan_buka_acc" TINYINT(1) [not null]
  "tujuan_buka_acc_ket" VARCHAR(50) [not null]
  "pengalaman_inv" TINYINT(1) [not null]
  "pengalaman_inv_ket" VARCHAR(50) [not null]
  "pengalaman_trans" TINYINT(1) [not null]
  "keluarga_bapebti" TINYINT(1) [not null]
  "pailit" TINYINT(1) [not null]
  "darurat_nama" VARCHAR(50) [not null]
  "darurat_alm_rumah1" VARCHAR(255) [not null]
  "darurat_alm_rumah2" VARCHAR(50) [not null]
  "darurat_alm_rumah3" VARCHAR(50) [not null]
  "darurat_kode_pos" INT(9) [not null]
  "darurat_telp" BIGINT(15) [not null]
  "darurat_hub" VARCHAR(25) [not null]
  "pekerjaan" TINYINT(1) [not null]
  "pekerjaan_ket" VARCHAR(50) [not null]
  "nama_persh" VARCHAR(50) [not null]
  "bidang_usaha" VARCHAR(25) [not null]
  "jabatan" VARCHAR(25) [not null]
  "lama_kerja" TINYINT(2) [not null]
  "lama_sebelumnya" TINYINT(2) [not null]
  "alm_kantor1" VARCHAR(255) [not null]
  "alm_kantor2" VARCHAR(50) [not null]
  "alm_kantor3" VARCHAR(50) [not null]
  "kode_pos_kantor" INT(9) [not null]
  "telp_kantor" BIGINT(15) [not null]
  "fax_kantor" BIGINT(15) [not null]
  "penghasilan" SMALLINT(1) [not null]
  "kekayaan" VARCHAR(50) [not null]
  "rumah_lokasi" VARCHAR(50) [not null]
  "nilai_njop" BIGINT(15) [not null]
  "deposit_bank_name" VARCHAR(50) [not null, default: ""]
  "deposit_bank" BIGINT(15) [not null]
  "jumlah" BIGINT(15) [not null]
  "lainnya" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "no_telp_bank1" BIGINT(15) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_tabungan1" SMALLINT(1) [not null]
  "jenis_tabungan1_ket" VARCHAR(25) [not null]
  "nama_bank2" VARCHAR(50) [not null]
  "cabang_bank2" VARCHAR(50) [not null]
  "no_acc_bank2" VARCHAR(50) [not null]
  "no_telp_bank2" BIGINT(15) [not null]
  "atas_nama_bank2" VARCHAR(50) [not null]
  "jenis_tabungan2" SMALLINT(1) [not null]
  "jenis_tabungan2_ket" VARCHAR(25) [not null]
  "email" VARCHAR(50) [not null]
  "pathdir" VARCHAR(6) [not null]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [not null]
  "cabang" INT(1) [not null, default: "0"]
  "107PBK01" INT(10) [not null, default: "0"]
  "107PBK021" INT(10) [not null, default: "0"]
  "107PBK022" INT(10) [not null, default: "0"]
  "107PBK03" INT(10) [not null, default: "0"]
  "XPPP" INT(10) [not null, default: "0"]
  "107PBK041" INT(10) [not null, default: "0"]
  "107PBK042" INT(10) [not null, default: "0"]
  "107PBK051" INT(10) [not null, default: "0"]
  "107PBK052" INT(10) [not null, default: "0"]
  "107PBK06" INT(10) [not null, default: "0"]
  "107PBK07" INT(10) [not null, default: "0"]
  "kepemilikan_dana" INT(10) [not null, default: "0"]
  "MODIFY_TIME" BIGINT(20) [not null]
}

Table "account_simple" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "tempat_lahir" VARCHAR(50) [not null]
  "day" INT(2) [not null, default: "0"]
  "month" INT(2) [not null, default: "0"]
  "year" INT(4) [not null, default: "0"]
  "id_type" TINYINT(1) [not null]
  "id_no" VARCHAR(25) [not null]
  "npwp_type" TINYINT(1) [not null, default: "0"]
  "npwp_no" VARCHAR(20) [not null]
  "kelamin" TINYINT(1) [not null]
  "nama_pasangan" VARCHAR(50) [not null]
  "nama_ibu" VARCHAR(50) [not null]
  "status_kawin" TINYINT(1) [not null]
  "alm_rumah1" VARCHAR(255) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_telp_rumah" BIGINT(15) [not null]
  "no_fax_rumah" BIGINT(15) [not null]
  "no_hp" BIGINT(15) [not null]
  "status_rumah" TINYINT(1) [not null]
  "ket_rumah" VARCHAR(25) [not null]
  "tujuan_buka_acc" TINYINT(1) [not null]
  "tujuan_buka_acc_ket" VARCHAR(50) [not null]
  "pengalaman_inv" TINYINT(1) [not null]
  "pengalaman_inv_ket" VARCHAR(50) [not null]
  "pengalaman_trans" TINYINT(1) [not null]
  "keluarga_bapebti" TINYINT(1) [not null]
  "pailit" TINYINT(1) [not null]
  "darurat_nama" VARCHAR(50) [not null]
  "darurat_alm_rumah1" VARCHAR(255) [not null]
  "darurat_alm_rumah2" VARCHAR(50) [not null]
  "darurat_alm_rumah3" VARCHAR(50) [not null]
  "darurat_kode_pos" INT(9) [not null]
  "darurat_telp" BIGINT(15) [not null]
  "darurat_hub" VARCHAR(25) [not null]
  "pekerjaan" TINYINT(1) [not null]
  "pekerjaan_ket" VARCHAR(50) [not null]
  "nama_persh" VARCHAR(50) [not null]
  "bidang_usaha" VARCHAR(25) [not null]
  "jabatan" VARCHAR(25) [not null]
  "lama_kerja" TINYINT(2) [not null]
  "lama_sebelumnya" TINYINT(2) [not null]
  "alm_kantor1" VARCHAR(255) [not null]
  "alm_kantor2" VARCHAR(50) [not null]
  "alm_kantor3" VARCHAR(50) [not null]
  "kode_pos_kantor" INT(9) [not null]
  "telp_kantor" BIGINT(15) [not null]
  "fax_kantor" BIGINT(15) [not null]
  "penghasilan" SMALLINT(1) [not null]
  "kekayaan" VARCHAR(50) [not null]
  "rumah_lokasi" VARCHAR(50) [not null]
  "nilai_njop" BIGINT(15) [not null]
  "deposit_bank_name" VARCHAR(50) [not null, default: ""]
  "deposit_bank" BIGINT(15) [not null]
  "jumlah" BIGINT(15) [not null]
  "lainnya" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "no_telp_bank1" BIGINT(15) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_tabungan1" SMALLINT(1) [not null]
  "jenis_tabungan1_ket" VARCHAR(25) [not null]
  "nama_bank2" VARCHAR(50) [default: NULL]
  "cabang_bank2" VARCHAR(50) [default: NULL]
  "no_acc_bank2" VARCHAR(50) [default: NULL]
  "no_telp_bank2" BIGINT(15) [default: NULL]
  "atas_nama_bank2" VARCHAR(50) [default: NULL]
  "jenis_tabungan2" SMALLINT(1) [default: NULL]
  "jenis_tabungan2_ket" VARCHAR(25) [default: NULL]
  "email" VARCHAR(50) [default: NULL]
  "pathdir" VARCHAR(6) [default: NULL]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [default: NULL]
  "cabang" INT(1) [not null, default: "0"]
  "PBKCDDS01" INT(10) [not null, default: "0"]
  "PBKCDDS021" INT(10) [not null, default: "0"]
  "PBKCDDS022" INT(10) [not null, default: "0"]
  "PBKCDDS03" INT(10) [not null, default: "0"]
  "PBKCDDS04" INT(10) [not null, default: "0"]
  "PBKCDDS051" INT(10) [not null, default: "0"]
  "PBKCDDS052" INT(10) [not null, default: "0"]
  "PBKCDDS061" INT(10) [not null, default: "0"]
  "PBKCDDS062" INT(10) [not null, default: "0"]
  "PBKCDDS07" INT(10) [not null, default: "0"]
  "PBKCDDS08" INT(10) [not null, default: "0"]
  "PBKCDDS09" INT(10) [not null, default: "0"]
  "PBKCDDS10" INT(10) [not null, default: "0"]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]
}

Table "api_user" {
  "clientid" INT(11) [pk, not null, increment]
  "userid" INT(5) [not null]
  "clientname" VARCHAR(20) [not null]
  "clientip" VARCHAR(150) [not null, default: "203.128.83.250"]
  "api_key" VARCHAR(20) [not null]
  "active" SMALLINT(1) [not null, default: "1"]
  "ValidateEmail" SMALLINT(1) [not null, default: "0"]
  "ValidateUserName" SMALLINT(1) [not null, default: "0"]
  "ValidateAffiliate" SMALLINT(1) [not null, default: "0"]
  "GetUserDetail" SMALLINT(1) [not null, default: "0"]
  "RegisterUser" SMALLINT(1) [not null, default: "0"]
  "RegisterAffiliate" SMALLINT(1) [not null, default: "0"]
  "IsInvestor" SMALLINT(1) [not null, default: "0"]
  "SendMailApi" SMALLINT(1) [not null, default: "0"]
  "ReqWithdraw" SMALLINT(1) [not null, default: "0"]
  "UploadImage" SMALLINT(1) [not null, default: "0"]
  "ReqAccountDemo" SMALLINT(1) [not null, default: "0"]
}

Table "askap_migrations" {
  "id" INT(11) [pk, not null, increment]
  "timestamp" BIGINT(20) [not null]
  "name" VARCHAR(255) [not null]
}

Table "askap_users" {
  "user_realname" VARCHAR(255) [not null, default: ""]
  "user_name" VARCHAR(150) [not null, default: ""]
  "user_email" VARCHAR(100) [not null, default: ""]
  "user_pass" VARCHAR(100) [not null, default: ""]
  "registerDate" DATETIME [not null, default: "0000-00-00 00:00:00"]
  "user_registered" INT(10) [not null]
  "curr_id" INT(5) [not null, default: "1"]
  "country_id" INT(3) [not null, default: "1"]

Indexes {
  user_name [name: "username"]
}
}

Table "autoupdate" {
  "user_email" VARCHAR(50) [pk, not null]
  "update_time" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
}

Table "companybank" {
  "bank_id" INT(5) [pk, not null, increment]
  "curr_id" INT(5) [not null]
  "bank_name" VARCHAR(100) [not null]
  "bank_acc_no" VARCHAR(20) [not null]
  "bank_acc_name" VARCHAR(100) [not null]
}

Table "countrylist" {
  "country_id" INT(3) [pk, not null, increment]
  "country_name" VARCHAR(100) [not null]
  "country_abbrv" VARCHAR(2) [not null]
  "curr_id" INT(5) [not null]
}

Table "currency" {
  "curr_id" INT(5) [pk, not null, increment]
  "curr_name" VARCHAR(10) [not null]
  "symbol" VARCHAR(50) [not null]
  "minnominal" INT(10) [not null, default: "0"]
}

Table "demo_contest_2013_1" {
  "user_id" INT(5) [not null]
  "user_mt4id" BIGINT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "alm_rumah1" VARCHAR(50) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_hp" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "demo_contest_2013_2" {
  "user_id" INT(5) [not null]
  "user_mt4id" BIGINT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "alm_rumah1" VARCHAR(50) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_hp" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "demo_contest_2013_3" {
  "user_id" INT(5) [not null]
  "user_mt4id" BIGINT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "alm_rumah1" VARCHAR(50) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_hp" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "demo_contest_2013_4" {
  "user_id" INT(5) [not null]
  "user_mt4id" BIGINT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "alm_rumah1" VARCHAR(50) [not null]
  "alm_rumah2" VARCHAR(50) [not null]
  "alm_rumah3" VARCHAR(50) [not null]
  "kode_pos_rumah" INT(9) [not null]
  "no_hp" BIGINT(15) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "deposit_fx" {
  "id" INT(10) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platid" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "nominal" DECIMAL(15,2) [not null]
  "plat_bankname" VARCHAR(100) [not null]
  "plat_bankaccno" VARCHAR(20) [not null]
  "plat_bankreg" VARCHAR(100) [not null]
  "time" INT(10) [not null]
  "tipe" TINYINT(1) [not null, default: "0"]
  "cashier" TINYINT(1) [not null, default: "0"]
  "settle" TINYINT(1) [not null, default: "0"]
  "paytime" INT(10) [not null]
  "paid" INT(1) [not null, default: "0"]
  "floating" INT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}

Table "deposit" {
  "id" INT(10) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platid" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "nominal" DECIMAL(15,2) [not null]
  "plat_bankname" VARCHAR(100) [not null]
  "plat_bankaccno" VARCHAR(20) [not null]
  "plat_bankreg" VARCHAR(100) [not null]
  "time" INT(10) [not null]
  "tipe" TINYINT(1) [not null, default: "0"]
  "cashier" TINYINT(1) [not null, default: "0"]
  "settle" TINYINT(1) [not null, default: "0"]
  "paytime" INT(10) [not null]
  "paid" INT(1) [not null, default: "0"]
  "floating" INT(1) [not null, default: "0", note: '0=fix10k, -1=fix12k, 1=floating']

Indexes {
  user_id [name: "user_id"]
}
}

Table "fbinvite" {
  "uid" BIGINT(15) [not null]
  "date" DATETIME [not null]
  "name" VARCHAR(50) [not null]
  "url" VARCHAR(50) [not null]
  "pp" VARCHAR(255) [not null]
  "friends" INT(11) [not null]

Indexes {
  (date, uid) [pk]
}
}

Table "keybca" {
  "klikPayCode" VARCHAR(10) [not null]
  "clearKey" VARCHAR(16) [not null]
}

Table "klikpay" {
  "trans_no" INT(11) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platid" VARCHAR(10) [not null]
  "nominal" INT(12) [not null]
  "submit_time" DATETIME [not null]
  "payment_time" DATETIME [not null]
  "deposit_id" INT(10) [not null]
  "status" TINYINT(1) [not null, default: "0"]
}

Table "log" {
  "id" INT(10) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "action" VARCHAR(25) [not null]
  "ip" VARCHAR(15) [not null]
  "browser" VARCHAR(255) [not null]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "lot" {
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(10) [not null]
  "year" INT(4) [not null]
  "jan" DECIMAL(10,2) [not null]
  "feb" DECIMAL(10,2) [not null]
  "mar" DECIMAL(10,2) [not null]
  "apr" DECIMAL(10,2) [not null]
  "may" DECIMAL(10,2) [not null]
  "jun" DECIMAL(10,2) [not null]
  "jul" DECIMAL(10,2) [not null]
  "aug" DECIMAL(10,2) [not null]
  "sep" DECIMAL(10,2) [not null]
  "oct" DECIMAL(10,2) [not null]
  "nov" DECIMAL(10,2) [not null]
  "des" DECIMAL(10,2) [not null]
  "time" INT(10) [not null]

Indexes {
  (year, user_id, mt4id) [pk]
}
}

Table "mail_fx" {
  "country_id" INT(3) [pk, not null]
  "subject_0" LONGTEXT [not null]
  "from_name_0" LONGTEXT [not null]
  "from_email_0" LONGTEXT [not null]
  "to_name_0" LONGTEXT [not null]
  "to_email_0" LONGTEXT [not null]
  "cc_name_0" LONGTEXT [not null]
  "cc_email_0" LONGTEXT [not null]
  "bcc_name_0" LONGTEXT [not null]
  "bcc_email_0" LONGTEXT [not null]
  "content_00" LONGTEXT [not null]
  "content_01" LONGTEXT [not null]
  "subject_1" LONGTEXT [not null]
  "from_name_1" LONGTEXT [not null]
  "from_email_1" LONGTEXT [not null]
  "to_name_1" LONGTEXT [not null]
  "to_email_1" LONGTEXT [not null]
  "cc_name_1" LONGTEXT [not null]
  "cc_email_1" LONGTEXT [not null]
  "bcc_name_1" LONGTEXT [not null]
  "bcc_email_1" LONGTEXT [not null]
  "content_10" LONGTEXT [not null]
  "content_11" LONGTEXT [not null]
  "subject_2" LONGTEXT [not null]
  "from_name_2" LONGTEXT [not null]
  "from_email_2" LONGTEXT [not null]
  "to_name_2" LONGTEXT [not null]
  "to_email_2" LONGTEXT [not null]
  "cc_name_2" LONGTEXT [not null]
  "cc_email_2" LONGTEXT [not null]
  "bcc_name_2" LONGTEXT [not null]
  "bcc_email_2" LONGTEXT [not null]
  "content_20" LONGTEXT [not null]
  "content_21" LONGTEXT [not null]
  "subject_3" LONGTEXT [not null]
  "from_name_3" LONGTEXT [not null]
  "from_email_3" LONGTEXT [not null]
  "to_name_3" LONGTEXT [not null]
  "to_email_3" LONGTEXT [not null]
  "cc_name_3" LONGTEXT [not null]
  "cc_email_3" LONGTEXT [not null]
  "bcc_name_3" LONGTEXT [not null]
  "bcc_email_3" LONGTEXT [not null]
  "content_30" LONGTEXT [not null]
  "content_31" LONGTEXT [not null]
  "subject_4" LONGTEXT [not null]
  "from_name_4" LONGTEXT [not null]
  "from_email_4" LONGTEXT [not null]
  "to_name_4" LONGTEXT [not null]
  "to_email_4" LONGTEXT [not null]
  "cc_name_4" LONGTEXT [not null]
  "cc_email_4" LONGTEXT [not null]
  "bcc_name_4" LONGTEXT [not null]
  "bcc_email_4" LONGTEXT [not null]
  "content_40" LONGTEXT [not null]
  "content_41" LONGTEXT [not null]
  "smtp_host" VARCHAR(50) [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(50) [not null]
  "subject_6" LONGTEXT [not null]
  "from_name_6" LONGTEXT [not null]
  "from_email_6" LONGTEXT [not null]
  "to_name_6" LONGTEXT [not null]
  "to_email_6" LONGTEXT [not null]
  "cc_name_6" LONGTEXT [not null]
  "cc_email_6" LONGTEXT [not null]
  "bcc_name_6" LONGTEXT [not null]
  "bcc_email_6" LONGTEXT [not null]
  "content_60" LONGTEXT [not null]
  "content_61" LONGTEXT [not null]
  "subject_7" LONGTEXT [not null]
  "from_name_7" LONGTEXT [not null]
  "from_email_7" LONGTEXT [not null]
  "to_name_7" LONGTEXT [not null]
  "to_email_7" LONGTEXT [not null]
  "cc_name_7" LONGTEXT [not null]
  "cc_email_7" LONGTEXT [not null]
  "bcc_name_7" LONGTEXT [not null]
  "bcc_email_7" LONGTEXT [not null]
  "content_70" LONGTEXT [not null]
  "content_71" LONGTEXT [not null]
  "subject_8" LONGTEXT [not null]
  "from_name_8" LONGTEXT [not null]
  "from_email_8" LONGTEXT [not null]
  "to_name_8" LONGTEXT [not null]
  "to_email_8" LONGTEXT [not null]
  "cc_name_8" LONGTEXT [not null]
  "cc_email_8" LONGTEXT [not null]
  "bcc_name_8" LONGTEXT [not null]
  "bcc_email_8" LONGTEXT [not null]
  "content_80" LONGTEXT [not null]
  "content_81" LONGTEXT [not null]
  "subject_9" LONGTEXT [not null]
  "from_name_9" LONGTEXT [not null]
  "from_email_9" LONGTEXT [not null]
  "to_name_9" LONGTEXT [not null]
  "to_email_9" LONGTEXT [not null]
  "cc_name_9" LONGTEXT [not null]
  "cc_email_9" LONGTEXT [not null]
  "bcc_name_9" LONGTEXT [not null]
  "bcc_email_9" LONGTEXT [not null]
  "content_90" LONGTEXT [not null]
  "content_91" LONGTEXT [not null]
  "subject_10" LONGTEXT [not null]
  "from_name_10" LONGTEXT [not null]
  "from_email_10" LONGTEXT [not null]
  "to_name_10" LONGTEXT [not null]
  "to_email_10" LONGTEXT [not null]
  "cc_name_10" LONGTEXT [not null]
  "cc_email_10" LONGTEXT [not null]
  "bcc_name_10" LONGTEXT [not null]
  "bcc_email_10" LONGTEXT [not null]
  "content_100" LONGTEXT [not null]
  "content_101" LONGTEXT [not null]
  "subject_11" LONGTEXT [not null]
  "from_name_11" LONGTEXT [not null]
  "from_email_11" LONGTEXT [not null]
  "to_name_11" LONGTEXT [not null]
  "to_email_11" LONGTEXT [not null]
  "cc_name_11" LONGTEXT [not null]
  "cc_email_11" LONGTEXT [not null]
  "bcc_name_11" LONGTEXT [not null]
  "bcc_email_11" LONGTEXT [not null]
  "content_110" LONGTEXT [not null]
  "content_111" LONGTEXT [not null]
  "subject_12" LONGTEXT [not null]
  "from_name_12" LONGTEXT [not null]
  "from_email_12" LONGTEXT [not null]
  "to_name_12" LONGTEXT [not null]
  "to_email_12" LONGTEXT [not null]
  "cc_name_12" LONGTEXT [not null]
  "cc_email_12" LONGTEXT [not null]
  "bcc_name_12" LONGTEXT [not null]
  "bcc_email_12" LONGTEXT [not null]
  "content_120" LONGTEXT [not null]
  "content_121" LONGTEXT [not null]
  "subject_13" LONGTEXT [not null]
  "from_name_13" LONGTEXT [not null]
  "from_email_13" LONGTEXT [not null]
  "to_name_13" LONGTEXT [not null]
  "to_email_13" LONGTEXT [not null]
  "cc_name_13" LONGTEXT [not null]
  "cc_email_13" LONGTEXT [not null]
  "bcc_name_13" LONGTEXT [not null]
  "bcc_email_13" LONGTEXT [not null]
  "content_130" LONGTEXT [not null]
  "content_131" LONGTEXT [not null]
  "subject_14" LONGTEXT [not null]
  "from_name_14" LONGTEXT [not null]
  "from_email_14" LONGTEXT [not null]
  "to_name_14" LONGTEXT [not null]
  "to_email_14" LONGTEXT [not null]
  "cc_name_14" LONGTEXT [not null]
  "cc_email_14" LONGTEXT [not null]
  "bcc_name_14" LONGTEXT [not null]
  "bcc_email_14" LONGTEXT [not null]
  "content_140" LONGTEXT [not null]
  "content_141" LONGTEXT [not null]
  "subject_15" LONGTEXT [not null]
  "from_name_15" LONGTEXT [not null]
  "from_email_15" LONGTEXT [not null]
  "to_name_15" LONGTEXT [not null]
  "to_email_15" LONGTEXT [not null]
  "cc_name_15" LONGTEXT [not null]
  "cc_email_15" LONGTEXT [not null]
  "bcc_name_15" LONGTEXT [not null]
  "bcc_email_15" LONGTEXT [not null]
  "content_150" LONGTEXT [not null]
  "content_151" LONGTEXT [not null]
  "subject_16" LONGTEXT [not null]
  "from_name_16" LONGTEXT [not null]
  "from_email_16" LONGTEXT [not null]
  "to_name_16" LONGTEXT [not null]
  "to_email_16" LONGTEXT [not null]
  "cc_name_16" LONGTEXT [not null]
  "cc_email_16" LONGTEXT [not null]
  "bcc_name_16" LONGTEXT [not null]
  "bcc_email_16" LONGTEXT [not null]
  "content_160" LONGTEXT [not null]
  "content_161" LONGTEXT [not null]
}

Table "mail" {
  "country_id" INT(3) [pk, not null]
  "subject_0" LONGTEXT [not null]
  "from_name_0" LONGTEXT [not null]
  "from_email_0" LONGTEXT [not null]
  "to_name_0" LONGTEXT [not null]
  "to_email_0" LONGTEXT [not null]
  "cc_name_0" LONGTEXT [not null]
  "cc_email_0" LONGTEXT [not null]
  "bcc_name_0" LONGTEXT [not null]
  "bcc_email_0" LONGTEXT [not null]
  "content_00" LONGTEXT [not null]
  "content_01" LONGTEXT [not null]
  "subject_1" LONGTEXT [not null]
  "from_name_1" LONGTEXT [not null]
  "from_email_1" LONGTEXT [not null]
  "to_name_1" LONGTEXT [not null]
  "to_email_1" LONGTEXT [not null]
  "cc_name_1" LONGTEXT [not null]
  "cc_email_1" LONGTEXT [not null]
  "bcc_name_1" LONGTEXT [not null]
  "bcc_email_1" LONGTEXT [not null]
  "content_10" LONGTEXT [not null]
  "content_11" LONGTEXT [not null]
  "subject_2" LONGTEXT [not null]
  "from_name_2" LONGTEXT [not null]
  "from_email_2" LONGTEXT [not null]
  "to_name_2" LONGTEXT [not null]
  "to_email_2" LONGTEXT [not null]
  "cc_name_2" LONGTEXT [not null]
  "cc_email_2" LONGTEXT [not null]
  "bcc_name_2" LONGTEXT [not null]
  "bcc_email_2" LONGTEXT [not null]
  "content_20" LONGTEXT [not null]
  "content_21" LONGTEXT [not null]
  "subject_3" LONGTEXT [not null]
  "from_name_3" LONGTEXT [not null]
  "from_email_3" LONGTEXT [not null]
  "to_name_3" LONGTEXT [not null]
  "to_email_3" LONGTEXT [not null]
  "cc_name_3" LONGTEXT [not null]
  "cc_email_3" LONGTEXT [not null]
  "bcc_name_3" LONGTEXT [not null]
  "bcc_email_3" LONGTEXT [not null]
  "content_30" LONGTEXT [not null]
  "content_31" LONGTEXT [not null]
  "subject_4" LONGTEXT [not null]
  "from_name_4" LONGTEXT [not null]
  "from_email_4" LONGTEXT [not null]
  "to_name_4" LONGTEXT [not null]
  "to_email_4" LONGTEXT [not null]
  "cc_name_4" LONGTEXT [not null]
  "cc_email_4" LONGTEXT [not null]
  "bcc_name_4" LONGTEXT [not null]
  "bcc_email_4" LONGTEXT [not null]
  "content_40" LONGTEXT [not null]
  "content_41" LONGTEXT [not null]
  "smtp_host" VARCHAR(50) [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(50) [not null]
  "subject_6" LONGTEXT [not null]
  "from_name_6" LONGTEXT [not null]
  "from_email_6" LONGTEXT [not null]
  "to_name_6" LONGTEXT [not null]
  "to_email_6" LONGTEXT [not null]
  "cc_name_6" LONGTEXT [not null]
  "cc_email_6" LONGTEXT [not null]
  "bcc_name_6" LONGTEXT [not null]
  "bcc_email_6" LONGTEXT [not null]
  "content_60" LONGTEXT [not null]
  "content_61" LONGTEXT [not null]
  "subject_7" LONGTEXT [not null]
  "from_name_7" LONGTEXT [not null]
  "from_email_7" LONGTEXT [not null]
  "to_name_7" LONGTEXT [not null]
  "to_email_7" LONGTEXT [not null]
  "cc_name_7" LONGTEXT [not null]
  "cc_email_7" LONGTEXT [not null]
  "bcc_name_7" LONGTEXT [not null]
  "bcc_email_7" LONGTEXT [not null]
  "content_70" LONGTEXT [not null]
  "content_71" LONGTEXT [not null]
  "subject_8" LONGTEXT [not null]
  "from_name_8" LONGTEXT [not null]
  "from_email_8" LONGTEXT [not null]
  "to_name_8" LONGTEXT [not null]
  "to_email_8" LONGTEXT [not null]
  "cc_name_8" LONGTEXT [not null]
  "cc_email_8" LONGTEXT [not null]
  "bcc_name_8" LONGTEXT [not null]
  "bcc_email_8" LONGTEXT [not null]
  "content_80" LONGTEXT [not null]
  "content_81" LONGTEXT [not null]
  "subject_9" LONGTEXT [not null]
  "from_name_9" LONGTEXT [not null]
  "from_email_9" LONGTEXT [not null]
  "to_name_9" LONGTEXT [not null]
  "to_email_9" LONGTEXT [not null]
  "cc_name_9" LONGTEXT [not null]
  "cc_email_9" LONGTEXT [not null]
  "bcc_name_9" LONGTEXT [not null]
  "bcc_email_9" LONGTEXT [not null]
  "content_90" LONGTEXT [not null]
  "content_91" LONGTEXT [not null]
  "subject_10" LONGTEXT [not null]
  "from_name_10" LONGTEXT [not null]
  "from_email_10" LONGTEXT [not null]
  "to_name_10" LONGTEXT [not null]
  "to_email_10" LONGTEXT [not null]
  "cc_name_10" LONGTEXT [not null]
  "cc_email_10" LONGTEXT [not null]
  "bcc_name_10" LONGTEXT [not null]
  "bcc_email_10" LONGTEXT [not null]
  "content_100" LONGTEXT [not null]
  "content_101" LONGTEXT [not null]
  "subject_11" LONGTEXT [not null]
  "from_name_11" LONGTEXT [not null]
  "from_email_11" LONGTEXT [not null]
  "to_name_11" LONGTEXT [not null]
  "to_email_11" LONGTEXT [not null]
  "cc_name_11" LONGTEXT [not null]
  "cc_email_11" LONGTEXT [not null]
  "bcc_name_11" LONGTEXT [not null]
  "bcc_email_11" LONGTEXT [not null]
  "content_110" LONGTEXT [not null]
  "content_111" LONGTEXT [not null]
  "subject_12" LONGTEXT [not null]
  "from_name_12" LONGTEXT [not null]
  "from_email_12" LONGTEXT [not null]
  "to_name_12" LONGTEXT [not null]
  "to_email_12" LONGTEXT [not null]
  "cc_name_12" LONGTEXT [not null]
  "cc_email_12" LONGTEXT [not null]
  "bcc_name_12" LONGTEXT [not null]
  "bcc_email_12" LONGTEXT [not null]
  "content_120" LONGTEXT [not null]
  "content_121" LONGTEXT [not null]
  "subject_13" LONGTEXT [not null]
  "from_name_13" LONGTEXT [not null]
  "from_email_13" LONGTEXT [not null]
  "to_name_13" LONGTEXT [not null]
  "to_email_13" LONGTEXT [not null]
  "cc_name_13" LONGTEXT [not null]
  "cc_email_13" LONGTEXT [not null]
  "bcc_name_13" LONGTEXT [not null]
  "bcc_email_13" LONGTEXT [not null]
  "content_130" LONGTEXT [not null]
  "content_131" LONGTEXT [not null]
  "subject_14" LONGTEXT [not null]
  "from_name_14" LONGTEXT [not null]
  "from_email_14" LONGTEXT [not null]
  "to_name_14" LONGTEXT [not null]
  "to_email_14" LONGTEXT [not null]
  "cc_name_14" LONGTEXT [not null]
  "cc_email_14" LONGTEXT [not null]
  "bcc_name_14" LONGTEXT [not null]
  "bcc_email_14" LONGTEXT [not null]
  "content_140" LONGTEXT [not null]
  "content_141" LONGTEXT [not null]
  "subject_15" LONGTEXT [not null]
  "from_name_15" LONGTEXT [not null]
  "from_email_15" LONGTEXT [not null]
  "to_name_15" LONGTEXT [not null]
  "to_email_15" LONGTEXT [not null]
  "cc_name_15" LONGTEXT [not null]
  "cc_email_15" LONGTEXT [not null]
  "bcc_name_15" LONGTEXT [not null]
  "bcc_email_15" LONGTEXT [not null]
  "content_150" LONGTEXT [not null]
  "content_151" LONGTEXT [not null]
  "subject_16" LONGTEXT [not null]
  "from_name_16" LONGTEXT [not null]
  "from_email_16" LONGTEXT [not null]
  "to_name_16" LONGTEXT [not null]
  "to_email_16" LONGTEXT [not null]
  "cc_name_16" LONGTEXT [not null]
  "cc_email_16" LONGTEXT [not null]
  "bcc_name_16" LONGTEXT [not null]
  "bcc_email_16" LONGTEXT [not null]
  "content_160" LONGTEXT [not null]
  "content_161" LONGTEXT [not null]
}

Table "mmb_whitelabel_manager_access" {
  "id" INT(11) [pk, not null, increment]
  "manager_id" INT(11) [not null]
  "company_id" INT(11) [not null]

Indexes {
  (manager_id, company_id) [unique, name: "manager_id_company_id"]
  manager_id [name: "manager_id"]
  company_id [name: "company_id"]
}
}

Table "mmb_whitelabel_manager" {
  "id" INT(11) [pk, not null, increment]
  "name" VARCHAR(50) [not null]
  "description" VARCHAR(50) [default: NULL]
  "secret_key" VARCHAR(96) [not null, default: "0"]
  "private_jwt_key" MEDIUMTEXT [default: NULL]
  "public_jwt_key" MEDIUMTEXT [default: NULL]

Indexes {
  secret_key [unique, name: "secret_key"]
}
}

Table "mmb_whitelabel" {
  "id" INT(11) [pk, not null, increment]
  "company" VARCHAR(96) [not null]
  "endpoint_url" TEXT [default: NULL]
  "additional_header" TEXT [default: NULL]
  "main_url" VARCHAR(128) [default: NULL]
  "ims_url" VARCHAR(128) [default: NULL]
  "symbol" VARCHAR(10) [not null, default: ""]

Indexes {
  company [unique, name: "mmb_whitelabel_company"]
  symbol [unique, name: "mmb_whitelabel_symbol"]
}
}

Table "mt4_server" {
  "id" TINYINT(1) [pk, not null, increment]
  "real" TINYINT(1) [not null, default: "0"]
  "ipaddress" VARCHAR(15) [not null]
  "type" VARCHAR(10) [not null]
  "active" TINYINT(1) [not null, default: "0"]

Indexes {
  real [name: "real"]
  active [name: "active"]
}
}

Table "remotelogin" {
  "platid" VARCHAR(10) [not null]
  "access_token" VARCHAR(32) [not null]
  "ip_address" VARCHAR(15) [not null]
  "time" INT(10) [not null]

Indexes {
  access_token [unique, name: "access_token"]
}
}

Table "report_abc" {
  "user_name" VARCHAR(20) [not null]
  "datetime" VARCHAR(25) [not null]
  "action" VARCHAR(25) [not null]
  "ip" VARCHAR(15) [not null]
  "browser" VARCHAR(255) [not null]
}

Table "search_log" {
  "id" INT(10) [pk, not null, increment]
  "query" LONGTEXT [not null]
}

Table "sms_respond" {
  "sukses" VARCHAR(160) [not null]
  "email" VARCHAR(160) [not null]
  "nomor" VARCHAR(160) [not null]
  "lain" VARCHAR(160) [not null]
}

Table "trash_users" {
  "user_id" INT(5) [not null]
  "user_level" SMALLINT(1) [not null, default: "1"]
  "aff_level" SMALLINT(1) [not null, default: "0"]
  "user_platid" VARCHAR(255) [not null]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(15) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "curr_id" INT(5) [not null]
  "country_id" INT(3) [not null]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [not null]
  "real_acc" SMALLINT(1) [not null, default: "0"]
  "verified" SMALLINT(1) [not null, default: "0"]
  "acc_type" SMALLINT(1) [not null, default: "0"]
  "jpsignal" INT(1) [not null, default: "0"]
  "affpath" TEXT [default: NULL]
  "id_fx" INT(11) [default: NULL]
  "ref_id_fx" INT(11) [default: NULL]
}

Table "users_demoid_fx" {
  "idx" INT(11) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "user_demoid" VARCHAR(21) [default: NULL]
  "password" VARCHAR(20) [not null]
  "indeks_demoid" VARCHAR(21) [not null]
  "indeks_password" VARCHAR(20) [not null]
  "reqtime" INT(10) [not null]
  "createtime" INT(10) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "platform" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}

Table "users_demoid" {
  "idx" INT(11) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "user_demoid" VARCHAR(21) [default: NULL]
  "password" VARCHAR(20) [not null]
  "indeks_demoid" VARCHAR(21) [not null]
  "indeks_password" VARCHAR(20) [not null]
  "reqtime" INT(10) [not null]
  "createtime" INT(10) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "platform" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}

Table "users_fx" {
  "user_id" INT(5) [pk, not null, increment]
  "user_level" SMALLINT(1) [not null, default: "1"]
  "aff_level" SMALLINT(1) [not null, default: "0"]
  "user_platid" VARCHAR(255) [not null]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(25) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "curr_id" INT(5) [not null, default: "1"]
  "country_id" INT(3) [not null, default: "1"]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [not null]
  "real_acc" SMALLINT(1) [not null, default: "0"]
  "verified" SMALLINT(1) [not null, default: "0"]
  "acc_type" SMALLINT(1) [not null, default: "0"]
  "jpsignal" INT(1) [not null, default: "0"]

Indexes {
  user_email [unique, name: "user_email"]
  user_referrer_id [name: "user_referrer_id"]
}
}

Table "users_groups_rules" {
  "group_id" INT(11) [not null]
  "rules_id" INT(11) [not null]

Indexes {
  (group_id, rules_id) [pk]
}
}

Table "users_groups" {
  "id" INT(11) [pk, not null, increment]
  "path" TEXT [not null]
  "groupname" VARCHAR(40) [not null]
}

Table "users_platid_del_fx" {
  "order_no" VARCHAR(22) [pk, not null]
  "order_time" INT(10) [not null]
  "order_status" SMALLINT(1) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "user_platid" VARCHAR(10) [default: NULL]
  "indeks_platid" VARCHAR(10) [default: NULL]
  "forex" TINYINT(1) [not null, default: "0"]
  "indeks" TINYINT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "demo_forex" VARCHAR(10) [not null]
  "demo_index" VARCHAR(10) [not null]
  "account" SMALLINT(1) [not null, default: "0"]
  "platform" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}

Table "users_platid_del" {
  "order_no" VARCHAR(22) [pk, not null]
  "order_time" INT(10) [not null]
  "order_status" SMALLINT(1) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "user_platid" VARCHAR(10) [default: NULL]
  "indeks_platid" VARCHAR(10) [default: NULL]
  "forex" TINYINT(1) [not null, default: "0"]
  "indeks" TINYINT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "demo_forex" VARCHAR(10) [not null]
  "demo_index" VARCHAR(10) [not null]
  "account" SMALLINT(1) [not null, default: "0"]
  "platform" TINYINT(1) [not null, default: "0"]
  "verifiedBy" INT(11) [default: NULL]

Indexes {
  user_id [name: "user_id"]
}
}

Table "users_platid_fx" {
  "order_no" VARCHAR(22) [pk, not null]
  "order_time" INT(10) [not null]
  "order_status" SMALLINT(1) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "user_platid" VARCHAR(10) [default: NULL]
  "indeks_platid" VARCHAR(10) [default: NULL]
  "forex" TINYINT(1) [not null, default: "0"]
  "indeks" TINYINT(1) [not null, default: "0"]
  "time" INT(10) [not null]
  "demo_forex" VARCHAR(10) [default: NULL]
  "demo_index" VARCHAR(10) [default: NULL]
  "account" SMALLINT(1) [not null, default: "0"]
  "platform" TINYINT(1) [not null, default: "0"]
  "verifiedBy" INT(11) [default: NULL]

Indexes {
  user_id [name: "user_id"]
  user_platid [name: "user_platid"]
  indeks_platid [name: "indeks_platid"]
}
}

Table "users_platid" {
  "order_no" VARCHAR(22) [pk, not null]
  "order_time" INT(10) [not null]
  "order_status" SMALLINT(1) [not null, default: "1", note: '2=quickreg, 3=form pbk03, 4=verified (compliance), 5=approved  (settlement), 6=refused (settlement)']
  "user_id" INT(5) [not null]
  "user_platid" VARCHAR(10) [default: NULL]
  "indeks_platid" VARCHAR(10) [default: NULL]
  "forex" TINYINT(1) [not null, default: "0"]
  "indeks" TINYINT(1) [not null, default: "0"]
  "time" INT(10) [not null, default: `unix_timestamp()`]
  "demo_forex" VARCHAR(10) [default: NULL]
  "demo_index" VARCHAR(10) [default: NULL]
  "account" SMALLINT(1) [not null, default: "0", note: '0 : Gold / Mini AskapSocial - 1 : Platinum / Reguler AskapSocial - 2 : Multilateral - 3 : Silver / Mini AskapFX']
  "platform" TINYINT(1) [not null, default: "0"]
  "verifiedBy" INT(11) [default: NULL]

Indexes {
  user_id [name: "user_id"]
  user_platid [name: "user_platid"]
  indeks_platid [name: "indeks_platid"]
}
}

Table "users_rules" {
  "id" INT(11) [pk, not null]
  "rules" VARCHAR(128) [not null]
  "state" TINYINT(4) [not null, default: "0"]

Indexes {
  rules [unique, name: "rules"]
  state [name: "state"]
}
}

Table "users" {
  "user_id" INT(5) [pk, not null, increment]
  "user_company" INT(11) [default: NULL]
  "user_level" SMALLINT(1) [not null, default: "1", note: '1:Trader, 20:Affiliate, 21:IB, 22:Master IB, 23:Marketing, 3:Compliance, 4:Settlement, 5:Cashier, 6:Admin, 7:Superadmin, 8:KBI']
  "aff_level" SMALLINT(1) [not null, default: "0"]
  "user_platid" VARCHAR(255) [not null]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(25) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "curr_id" INT(5) [not null, default: "1"]
  "country_id" INT(3) [not null, default: "1"]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [default: NULL, note: 'first_ref']
  "last_ref" VARCHAR(255) [default: NULL]
  "first_visit" VARCHAR(255) [default: NULL]
  "goal_ref" VARCHAR(255) [default: NULL]
  "real_acc" SMALLINT(1) [not null, default: "0"]
  "verified" SMALLINT(1) [not null, default: "0"]
  "acc_type" SMALLINT(1) [not null, default: "0"]
  "jpsignal" INT(1) [not null, default: "0"]
  "affpath" TEXT [default: NULL]
  "id_fx" INT(11) [default: NULL]
  "ref_id_fx" INT(11) [default: NULL]

Indexes {
  user_name [unique, name: "user_name"]
  user_referrer_id [name: "user_referrer_id"]
  user_email [name: "user_email"]
  user_registered [name: "user_registered"]
}
}

Table "withdrawal_fx" {
  "id" INT(5) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platid" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "nominal" DECIMAL(15,2) [not null, default: "0.00"]
  "time" INT(10) [not null]
  "tipe" TINYINT(1) [not null, default: "2"]
  "cashier" TINYINT(1) [not null, default: "0"]
  "settle" TINYINT(1) [not null, default: "0"]
  "idr" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}

Table "withdrawal" {
  "id" INT(5) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platid" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "nominal" DECIMAL(15,2) [not null, default: "0.00"]
  "time" INT(10) [not null]
  "tipe" TINYINT(1) [not null, default: "2"]
  "cashier" TINYINT(1) [not null, default: "0"]
  "settle" TINYINT(1) [not null, default: "0"]
  "idr" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}
