Table "account_corporate" {
  "order_no" VARCHAR(22) [pk, not null]
  "nama" VARCHAR(50) [not null]
  "alamat_persh1" VARCHAR(50) [not null]
  "alamat_persh2" VARCHAR(50) [not null]
  "alamat_persh3" VARCHAR(50) [not null]
  "kodepos_persh" INT(9) [not null]
  "telp_persh" BIGINT(15) [not null]
  "fax_persh" BIGINT(15) [not null]
  "hp_persh" BIGINT(15) [not null]
  "email_persh" VARCHAR(50) [not null]
  "nama_bank" VARCHAR(50) [not null]
  "cabang_bank" VARCHAR(50) [not null]
  "no_acc_bank" VARCHAR(20) [not null]
  "atas_nama_bank" VARCHAR(50) [not null]
  "jenis_rekening" SMALLINT(1) [not null]
  "jenis_rekening_ket" VARCHAR(25) [not null]
  "pemegang_saham1" VARCHAR(50) [not null]
  "pemegang_saham2" VARCHAR(50) [not null]
  "pemegang_saham3" VARCHAR(50) [not null]
  "pemegang_saham4" VARCHAR(50) [not null]
  "nama_pengurus1" VARCHAR(50) [not null]
  "jabatan_pengurus1" VARCHAR(25) [not null]
  "alamat_pengurus1" VARCHAR(100) [not null]
  "telp_pengurus1" BIGINT(15) [not null]
  "fax_pengurus1" BIGINT(15) [not null]
  "id_type_pengurus1" SMALLINT(1) [not null]
  "id_no_pengurus1" VARCHAR(25) [not null]
  "nama_pengurus2" VARCHAR(50) [not null]
  "jabatan_pengurus2" VARCHAR(25) [not null]
  "alamat_pengurus2" VARCHAR(100) [not null]
  "telp_pengurus2" BIGINT(15) [not null]
  "fax_pengurus2" BIGINT(15) [not null]
  "id_type_pengurus2" SMALLINT(1) [not null]
  "id_no_pengurus2" VARCHAR(25) [not null]
  "nama_pengurus3" VARCHAR(50) [not null]
  "jabatan_pengurus3" VARCHAR(25) [not null]
  "alamat_pengurus3" VARCHAR(100) [not null]
  "telp_pengurus3" BIGINT(15) [not null]
  "fax_pengurus3" BIGINT(15) [not null]
  "id_type_pengurus3" SMALLINT(1) [not null]
  "id_no_pengurus3" VARCHAR(25) [not null]
  "nama_pengurus4" VARCHAR(50) [not null]
  "jabatan_pengurus4" VARCHAR(25) [not null]
  "alamat_pengurus4" VARCHAR(100) [not null]
  "telp_pengurus4" BIGINT(15) [not null]
  "fax_pengurus4" BIGINT(15) [not null]
  "id_type_pengurus4" SMALLINT(1) [not null]
  "id_no_pengurus4" VARCHAR(25) [not null]
  "nama_pejabat" VARCHAR(50) [not null]
  "jabatan_pejabat" VARCHAR(25) [not null]
  "alamat_pejabat" VARCHAR(100) [not null]
  "telp_pejabat" BIGINT(15) [not null]
  "fax_pejabat" BIGINT(15) [not null]
  "id_type_pejabat" SMALLINT(1) [not null]
  "id_no_pejabat" VARCHAR(25) [not null]
  "pathdir" VARCHAR(6) [not null]
  "perselisihan" SMALLINT(1) [not null, default: "0"]
  "pengadilan" VARCHAR(30) [not null]
}
