Table "account_marketing_mtc" {
  "acc" VARCHAR(20) [not null]
  "platform" VARCHAR(10) [not null, default: "mt4"]
  "marketing" INT(11) [not null, default: "0", note: 'maintenance']
  "active" DATETIME [not null]
  "chop" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]

Indexes {
  acc [name: "mt4acc"]
  marketing [name: "marketing"]
}
}
