Table "api_user" {
  "clientid" INT(11) [pk, not null, increment]
  "userid" INT(5) [not null]
  "clientname" VARCHAR(20) [not null]
  "clientip" VARCHAR(150) [not null, default: "203.128.83.250"]
  "api_key" VARCHAR(20) [not null]
  "active" SMALLINT(1) [not null, default: "1"]
  "ValidateEmail" SMALLINT(1) [not null, default: "0"]
  "ValidateUserName" SMALLINT(1) [not null, default: "0"]
  "ValidateAffiliate" SMALLINT(1) [not null, default: "0"]
  "GetUserDetail" SMALLINT(1) [not null, default: "0"]
  "RegisterUser" SMALLINT(1) [not null, default: "0"]
  "RegisterAffiliate" SMALLINT(1) [not null, default: "0"]
  "IsInvestor" SMALLINT(1) [not null, default: "0"]
  "SendMailApi" SMALLINT(1) [not null, default: "0"]
  "ReqWithdraw" SMALLINT(1) [not null, default: "0"]
  "UploadImage" SMALLINT(1) [not null, default: "0"]
  "ReqAccountDemo" SMALLINT(1) [not null, default: "0"]
}
