Table "askap_users" {
  "user_realname" VARCHAR(255) [not null, default: ""]
  "user_name" VARCHAR(150) [not null, default: ""]
  "user_email" VARCHAR(100) [not null, default: ""]
  "user_pass" VARCHAR(100) [not null, default: ""]
  "registerDate" DATETIME [not null, default: "0000-00-00 00:00:00"]
  "user_registered" INT(10) [not null]
  "curr_id" INT(5) [not null, default: "1"]
  "country_id" INT(3) [not null, default: "1"]

Indexes {
  user_name [name: "username"]
}
}
