Table "trash_users" {
  "user_id" INT(5) [not null]
  "user_level" SMALLINT(1) [not null, default: "1"]
  "aff_level" SMALLINT(1) [not null, default: "0"]
  "user_platid" VARCHAR(255) [not null]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(15) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "curr_id" INT(5) [not null]
  "country_id" INT(3) [not null]
  "user_bankname" VARCHAR(100) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [not null]
  "real_acc" SMALLINT(1) [not null, default: "0"]
  "verified" SMALLINT(1) [not null, default: "0"]
  "acc_type" SMALLINT(1) [not null, default: "0"]
  "jpsignal" INT(1) [not null, default: "0"]
  "affpath" TEXT [default: NULL]
  "id_fx" INT(11) [default: NULL]
  "ref_id_fx" INT(11) [default: NULL]
}
